name: "Draw Keymap"

on:
  workflow_dispatch:
  # push時に自動で実行する場合は、以下のコメントアウトを外す
  # push:
  #   paths:
  #     - "config/LAMA.keymap"
  #     - "keymap_drawer.config.yaml"
  #     - "boards/shields/LAMA/LAMA.dtsi"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      commit_message: "[Draw] ${{ github.event.head_commit.message || 'Update keymap drawing' }}"
      amend_commit: false
      keymap_patterns: "config/*.keymap"
      json_path: "config"
      config_path: "keymap_drawer.config.yaml"
      output_folder: "keymap-drawer"
      destination: "both"
